## pyESM - Python based Engineering Systems Modelling (pyESM)
Python based engineering systems modelling framework based on the Supply and Use structure

- - -
PACKAGE LOCAL INSTALLATION and USAGE

Editable local installation:
1. Create a virtual environment based on 'environment.yml' file.
2. In the cmd, run: >>> python -m pip install -e "path/to/pyesm"
3. From the virtual environment: >>> import esm
4. Use esm APIs (Model class)


- - -
CREATE/UPDATE ENVIRONMENT BASED ON YML FILE IN PROJECT REPO

In the prompt:
- From the path where environment.yml is present: >>> conda env create -f environment.yml
- The environment is named "esm", so type >>> conda activate esm

UPDATE ENVIRONMENT YML FILE (in case of modifications)

In the prompt: 
- activate the working environment: >>> conda activate your_environment_name
- export environment.yml file based on the working environment: >>> conda env export > environment.yml


- - - 
MODEL DIRECTORY GENERATION

Generation of a model directory based on a model template or with blank setup files.

In [ ]:
# create model directory with essential setup files
# to be used only to generate models from scratch
# template models can be imported 
import esm

model_dir_name = '4_sut_multi_year_rcot_vb'
main_dir_path = r'c:\Users\baioc\Documents\GitHub\pyesm\default'

esm.create_model_dir(
    model_dir_name=model_dir_name,
    main_dir_path=main_dir_path,
    default_model=None,
    force_overwrite=False,
)

- - - 
GENERATION OF A NEW MODEL FROM SCRATCH

Generation of a new model defined by setup files.

Step-by-step model creation with sets, data and problems generation.

In [1]:
# generate model instance based on setup files filled by the user.
# validates model directory before executing.
import esm

model_dir_name = '4_sut_multi_year_rcot_cap_new'
main_dir_path = 'D:/git_repos/pyesm/default'

model = esm.Model(
    model_dir_name=model_dir_name,
    main_dir_path=main_dir_path,
    use_existing_data=False,
)

INFO | Model | 'Model' object initialization...
INFO | Model.file_manager | 'FileManager' object generated.
INFO | Model | Defining settings from model arguments.
INFO | Model | Defining paths from model arguments.
INFO | Model | Model directory and required setup files validated.
INFO | Model.core | 'Core' object initialization...
INFO | Model.core.sql_manager | 'SQLManager' object generation.
INFO | Model.core.index | 'Index' object initialization...
INFO | Model.core.index | Loading and validating data from file, generating 'SetTable' objects.
DEBUG | Model.file_manager | File 'structure_sets.yml' loaded.
INFO | Model.core.index | Loading and validating data from file, generating 'DataTable' objects.
DEBUG | Model.file_manager | File 'structure_variables.yml' loaded.
INFO | Model.core.index | Fetching and validating data, generating 'Variable' objects.
DEBUG | Model.core.index | Fetching 'coordinates_info' to Index.variables.
INFO | Model.core.index | 'Index' object initialized.
INF

In [2]:
# after filling sets.xlsx file: 
# - loading model coordinates to Index
# - generating sqlite database tables for sets and variables
# (variables tables in sqlite database empty)
model.load_model_coordinates()
model.initialize_blank_database()

INFO | Model | Loading new sets data and variable coordinates.
INFO | Model.core.index | 'Index' object: loading new Sets data to Index.sets.
DEBUG | Model.file_manager | Excel file 'sets.xlsx' loaded.
INFO | Model.core.index | 'Index' object: loading variable coordinates to Index.data.
INFO | Model.core.index | 'Index' object: loading variable coordinates to Index.variables.
INFO | Model.core.index | Loading tables 'foreign_keys' to Index.data_tables.
INFO | Model | Generating blank SQLite database and excel input files.
DEBUG | Model.core.sql_manager | Connection to 'database.db' opened.
INFO | Model.core.database | Loading Sets to 'database.db'.
DEBUG | Model.core.sql_manager | SQLite table '_set_SCENARIOS' - table overwritten and 1 entries added.
DEBUG | Model.core.sql_manager | SQLite table '_set_TECH_SUP' - table overwritten and 3 entries added.
DEBUG | Model.core.sql_manager | SQLite table '_set_TECH_DEM' - table overwritten and 1 entries added.
DEBUG | Model.core.sql_manager | 

In [3]:
# after filling input_data file/s:
# - loading input data into sqlite database variables tables
# - initialize problem
model.load_data_files_to_database()
model.initialize_problems()

INFO | Model | Loading input data to SQLite database.
DEBUG | Model.core.sql_manager | Connection to 'database.db' opened.
INFO | Model.core.database | Loading data input file/s filled by the user to SQLite database.
DEBUG | Model.file_manager | Excel file 'input_data.xlsx' loaded.
DEBUG | Model.core.sql_manager | SQLite table 'd' - 9 entries updated.
DEBUG | Model.core.sql_manager | SQLite table 'u' - 6 entries updated.
DEBUG | Model.core.sql_manager | SQLite table 'c' - 6 entries updated.
DEBUG | Model.core.sql_manager | SQLite table 'Y' - 10 entries updated.
DEBUG | Model.core.sql_manager | SQLite table 'c_start' - 3 entries updated.
DEBUG | Model.core.sql_manager | SQLite table 'e' - 3 entries updated.
DEBUG | Model.core.sql_manager | SQLite table 'lf_range' - 6 entries updated.
DEBUG | Model.core.sql_manager | Connection to 'database.db' closed.
DEBUG | Model.core.sql_manager | Connection to 'database.db' opened.
INFO | Model.core.database | Auto-completion of blank data in SQLite

- - - 
MODEL GENERATION FROM EXISTING DATA

Generation of a new model working with existing database and data input files.

In [1]:
# generate model instance based on setup files filled by the user.
# validates model directory (in case user relies on existing directory). 
# parse settings and paths.
# loading model coordinates
# initializing numerical problem
import esm 

model_dir_name = '4_sut_multi_year_rcot_cap_new'
main_dir_path = 'D:/git_repos/pyesm/default'

model = esm.Model(
    model_dir_name=model_dir_name,
    main_dir_path=main_dir_path,
    use_existing_data=True,
    log_level='info'
)

INFO | Model | 'Model' object initialization...
INFO | Model.file_manager | 'FileManager' object generated.
INFO | Model | Defining settings from model arguments.
INFO | Model | Defining paths from model arguments.
INFO | Model | Model directory and required setup files validated.
INFO | Model.core | 'Core' object initialization...
INFO | Model.core.sql_manager | 'SQLManager' object generation.
INFO | Model.core.index | 'Index' object initialization...
INFO | Model.core.index | Loading and validating data from file, generating 'SetTable' objects.
INFO | Model.core.index | Loading and validating data from file, generating 'DataTable' objects.
INFO | Model.core.index | Fetching and validating data, generating 'Variable' objects.
INFO | Model.core.index | 'Index' object initialized.
INFO | Model.core.database | 'Database' object initialization...
INFO | Model.core.database | 'Database' object initialized.
INFO | Model.core.problem | 'Problem' object initialization...
INFO | Model.core.pro

- - -
DATA and MODEL UPDATE, MODEL RUN 

updating SQLite database with new data, 
re-initializing numerical problem

solving numerical model, 
results export to sqlite database, 
generation of powerbi dataset

In [ ]:
# in case of modifications in input data files (but not in sets, nor in 
# variables structures), update database and problem only
model.update_database_and_problem()

In [ ]:
# in case of modifications in symbolic problem only,
# update problems dataframe and symbolic problem
model.initialize_problems()

In [4]:
# solve numerical problems
model.run_model(verbose=False)

INFO | Model | Running numerical model.
INFO | Model.core.problem | Solving problem: ['baseline'].


Set parameter Username
Academic license - for non-commercial use only - expires 2024-12-19


INFO | Model.core.problem | Problem status: 'optimal'


In [ ]:
# once model has successfully solved, load endogenous parameters data to 
# sqlite database and generate powerbi dataset.
model.load_results_to_database()
model.generate_pbi_report()

- - - 
TESTS

In [42]:
model.core.index.variables.u.none_data_coordinates(0)

In [9]:
for var_key, variable in model.core.index.variables.items():
    print(
        var_key, '\t\t',
        variable.shape, ' ',
        'shape_size:', variable.shape_size, ' ',
        # 'is_square:', variable.is_square, ' ',
        # 'is_vector:', variable.is_vector, ' ',
        # 'dim_labels:', variable.dim_labels, ' ',
        # 'dim_items:', variable.dim_items, ' ',
    )



d 		 ['technologies_supply', 'flows']   shape_size: [3, 3]  
u 		 ['flows_agg', 'technologies_supply']   shape_size: [2, 3]  
c_cap 		 ['costs', 'technologies_supply']   shape_size: [1, 3]  
c_om 		 ['costs', 'technologies_supply']   shape_size: [1, 3]  
Y 		 ['flows_agg', 'technologies_demand']   shape_size: [2, 1]  
c_start 		 [1, 'technologies_supply']   shape_size: [1, 3]  
e 		 ['emissions', 'technologies_supply']   shape_size: [1, 3]  
lf_max 		 ['load_factors', 'technologies_supply']   shape_size: [1, 3]  
lf_min 		 ['load_factors', 'technologies_supply']   shape_size: [1, 3]  
T_yy 		 ['years', 'years']   shape_size: [5, 5]  
I_ff 		 ['flows_agg', 'flows']   shape_size: [2, 3]  
X 		 ['technologies_supply', 1]   shape_size: [3, 1]  
Q 		 [1, 'flows']   shape_size: [1, 3]  
Q_agg 		 ['flows_agg', 1]   shape_size: [2, 1]  
C_cap 		 ['costs', 'technologies_supply']   shape_size: [1, 3]  
C_om 		 ['costs', 'technologies_supply']   shape_size: [1, 3]  
X_max 		 ['load_factors', 'tec

In [ ]:
model.core.index.variables

In [ ]:
model.core.index.sets.technologies

In [ ]:
model.core.problem.symbolic_problem

In [ ]:
model.core.problem.numeric_problems

In [ ]:
import cvxpy as cp
import numpy as np

# Problem data.
m = 5
n = 2

# Construct the problem.
x = cp.Variable((n,1))
A = cp.Constant(np.random.randn(m, n))
b = cp.Constant(1)


C = cp.Constant(np.random.randn(n, n))
I = cp.Constant(np.eye(n))

objective = cp.Minimize(cp.sum_squares(A @ x - b))
constraints = [0 <= x, x <= 1]
prob = cp.Problem(objective, constraints)

# The optimal objective value is returned by `prob.solve()`.
result = prob.solve(solver='GUROBI', verbose=False)
# The optimal value for x is stored in `x.value`.

x.value


In [ ]:
import numpy as np

array = np.ndarray()

In [24]:
import numpy as np
import cvxpy as cp


v_parent = cp.Variable((3,4))

v_parameter = cp.Parameter((3,4))
v_parameter.value = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
])

v_child = v_parent[0:1,0:2]

objective = cp.Minimize(1)
constraints = [v_parameter == v_parent]
prob = cp.Problem(objective, constraints)
prob.solve(solver='GUROBI')

print(f'v_parent = {v_parent.value} \n')
print(f'v_parameter = {v_parameter.value} \n')
print(f'v_child = {v_child.value} \n')

type(v_child)

v_parent = [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]] 

v_parameter = [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

v_child = [[1. 2.]] 



cvxpy.atoms.affine.index.index

In [ ]:
# DEFINIZIONE COSTANTI PER TRASFORMARE I VARI OPERATORI VETTORIALI
import cvxpy as cp
import numpy as np

var_a = cp.Variable((3,2))
var_a.value = np.ones((var_a.shape))*3
var_b = cp.Variable((3,1))

i_21 = cp.Constant(np.ones((2,1)))
i_13 = cp.Constant(np.ones((1,3)))

allowed_vars = {
    'A': var_a,
    'B': var_b,
    'i_21': i_21,
    'i_13': i_13,
}

allowed_ops = {
    '+': '+',
    '-': '-',
    '*': '*',
    '@': '@',
    '==': '==',
    '>=': '>=',
    '<=': '<=',
    '(': '(',
    ')': ')',
    ',':',',
    'sum': cp.sum,
}

expr = model.core.problem.execute_cvxpy_code(
    expression='i_13 @ A @ i_21',
    allowed_variables=allowed_vars,
    allowed_operators=allowed_ops
)

expr2 = model.core.problem.execute_cvxpy_code(
    expression='sum(B)',
    allowed_variables=allowed_vars,
    allowed_operators=allowed_ops
)

expr

In [ ]:
model.core.database.sqltools.open_connection()

var = model.core.database.sqltools.filtered_table_to_dataframe(
    table_name='u',
    filters_dict={
        's_Name': ['Reference'],
        'dt_Name': [2023],
        'f_Name': ['Energy', 'Steel'],
        't_Name': ['PV power plant', 'Steel factory', 'Gas power plant']
    }
)

# filter_1 = test.core.database.sqltools.get_related_table_keys(
#     child_column_name='f_Name',
#     parent_table_name='_set_FLOWS',
#     parent_table_fields={
#         'f_Category': ['Product flow'],
#     }
# )

# filter_2 = test.core.database.sqltools.get_related_table_keys(
#     child_column_name='dt_Name',
#     parent_table_name='_set_DATETIME',
#     parent_table_fields={
#         'dt_Name': [2023],
#     }
# )

# var_custom_filter = test.core.database.sqltools.filtered_table_to_dataframe(
#     table_name='v',
#     filters_dict={
#         **filter_1,
#         **filter_2,
#         **{'f_Name': ['Steel']},
#     }
# )

model.core.database.sqltools.close_connection()

# filter_1, filter_2
var